### ISSUE TITLE
example中navigator Observer中didPush和didPop都应当先触发pageEnd，再触发pageStart

### ISSUE THREAD

**Issue by huntrist** [flmn/umeng_analytics_plugin#2]
如didPush应当类似
```
void didPush(Route route, Route previousRoute) async {
    super.didPush(route, previousRoute);
    await UmengAnalytics.pageEnd(previousRoute.settings.name);
    await UmengAnalytics.pageStart(route.settings.name);
  }
```

**Comment by flmn** [comment]
didPush 处理 pageStart，didPop 处理 pageEnd，如果都处理的话，会有重复数据吧。

**Comment by huntrist** [comment]
打开umeng的log的话，消息会说，需要统计新页面的话，必须先pageEnd之前的那一页。
如果didPush只pageStart的话，连续push多页会造成只有pageStart没有pageEnd，不符合umeng的成对调用。
所以didPush要pageEnd previousRoute （如果有的话 - 因为有可能是第一页），pageSart route
didPop要pageEnd route，pageStart previousRoute (previousRoute是pop后显示的那一页）
其实还有didReplace需要处理，需要endPage oldRoute（如果有的话 - 因为有可能是第一页），startPage newRoute
这样就是成对调用了。
每次pageStart之前一定pageEnd了前一个展示的页面。

如果我没有理解错友盟的信息的话。。。

其实这样还是会在一些情况下造成 pageStart，pageEnd不成对调用的问题
如APP debug的时候push进去一些页面，然后直接强制重启，之后的navigate就都会显示没有成对调用的消息。怀疑是因为直接强制重启APP，造成了最后一个pageEnd没有发送。。。之后又复用了之前的session，然后就造成了之后的调用都错位。。。

**Comment by flmn** [comment]
> 打开umeng的log的话，消息会说，需要统计新页面的话，必须先pageEnd之前的那一页。
> 如果didPush只pageStart的话，连续push多页会造成只有pageStart没有pageEnd，不符合umeng的成对调用。
> 所以didPush要pageEnd previousRoute （如果有的话 - 因为有可能是第一页），pageSart route
> didPop要pageEnd route，pageStart previousRoute (previousRoute是pop后显示的那一页）
> 其实还有didReplace需要处理，需要endPage oldRoute（如果有的话 - 因为有可能是第一页），startPage newRoute
> 这样就是成对调用了。
> 每次pageStart之前一定pageEnd了前一个展示的页面。
> 
> 如果我没有理解错友盟的信息的话。。。
> 
> 其实这样还是会在一些情况下造成 pageStart，pageEnd不成对调用的问题
> 如APP debug的时候push进去一些页面，然后直接强制重启，之后的navigate就都会显示没有成对调用的消息。怀疑是因为直接强制重启APP，造成了最后一个pageEnd没有发送。。。之后又复用了之前的session，然后就造成了之后的调用都错位。。。

你说的有道理。
