### ISSUE TITLE
debug环境能正常统计，正式包没有统计数据

### ISSUE THREAD

**Issue by ghost** [flmn/umeng_analytics_plugin#9]
不知道是什么原因，正式包没有统计数据而debug包有。我的包的minsdk设置为16，还添加了 <uses-sdk tools:overrideLibrary="tech.jitao.umeng_analytics_plugin"> 不清楚是不是这个引起的。。。

**Comment by Pluto1219** [comment]
> 不知道是什么原因，正式包没有统计数据而debug包有。我的包的minsdk设置为16，还添加了 不清楚是不是这个引起的。。。
怎么好的
